version: "3.9"

services:

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agriculture_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql


  api:
    build: .
    container_name: fastapi_app

    restart: always

    depends_on:
      - db

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: mysql+pymysql://user:user123@db:3306/Agri_Malade

volumes:
  mysql_data: